on:
  schedule:
  - cron: '0 4 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
    - run: |
        curl -sI -H 'Accept: application/vnd.oci.image.manifest.v1+json' https://quay.io/v2/fedora/fedora-bootc/manifests/latest | \
        grep -i 'docker-content-digest:' | tr -d '\r' | awk '{print "BASE_VERSION=@"$2}' > argfile.conf
    - run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - run: |
        if git commit -a -m "auto-update"; then
          echo "Base image changed, skipping package check."
        else
          podman run --rm --pull=always "ghcr.io/${{ github.repository }}:latest" \
            bash -c 'dnf --repo=updates list --available $(cat /usr/share/misc/additional_packages.txt)' > available_packages.txt
          git commit -a -m "auto-update" || echo "Nothing to commit"
        fi
        git push
