on:
  push:
    branches:
    - master
  schedule:
  - cron: '0 4 * * *'
  workflow_dispatch:
permissions:
  packages: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - run: |
        from=quay.io/fedora/fedora-bootc:latest
        docker pull "$from"
        digest=$(docker image inspect "$from" | jq -r .[0].RepoDigests[0])
        echo "$digest" > digest.txt
        echo "BASE_IMAGE=$digest" >> $GITHUB_ENV
        docker run --rm ghcr.io/${{ github.repository }}:latest bash -c 'dnf --repo=updates list --available $(cat /usr/share/misc/additional_packages.txt)' > packages.txt
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -a -m "auto-update" || echo "UP_TO_DATE=true" >> $GITHUB_ENV
        git push
    - uses: docker/build-push-action@v6
      if: env.UP_TO_DATE != 'true' || github.event_name == 'push'
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        build-args: BASE_IMAGE=${{ env.BASE_IMAGE }}

