on:
  push:
    branches:
    - master
  workflow_dispatch:
permissions:
  packages: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: podman build --pull=always --build-arg-file=argfile.conf --tag "localhost/${{ github.repository }}" .
    - run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u "${{ github.actor }}" --password-stdin
    - run: podman push "localhost/${{ github.repository }}" "ghcr.io/${{ github.repository }}:latest"
    - run: podman run --rm "localhost/${{ github.repository }}" bash -c 'dnf --repo=updates list --available $(cat /usr/share/misc/additional_packages.txt)' > available_packages.txt
    - run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - run: |
        git commit -a -m "update additional_packages.txt" || echo "Nothing to commit"
        git push
