on:
  push:
    branches:
    - master
  schedule:
  - cron: '0 4 * * *'
  workflow_dispatch:
permissions:
  packages: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - run: docker run --rm ghcr.io/${{ github.repository }}:latest bash -c 'dnf --repo=updates list --available $(cat /usr/share/misc/additional_packages.txt)' > packages.txt
    - uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
    - run: docker image inspect ghcr.io/${{ github.repository }}:latest | jq -r .[0].Digest > digest.txt
    - run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -a -m "auto-update" || echo "Nothing to commit"
        git push
